# Generated by Django 4.0.5 on 2022-06-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_paig',
            options={'verbose_name': 'Стартовый блок', 'verbose_name_plural': 'Стартовые блоки'},
        ),
        migrations.AlterField(
            model_name='main_paig',
            name='content',
            field=models.TextField(max_length=200, verbose_name='Пояснительный текст'),
        ),
        migrations.AlterField(
            model_name='main_paig',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='main_paig',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
