# Generated by Django 4.0.5 on 2022-06-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uslugi',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='uslugi',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Уточнение'),
        ),
        migrations.AlterField(
            model_name='uslugi',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
