# Generated by Django 4.0.5 on 2022-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Период')),
                ('content', models.TextField(max_length=200, verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Стартовый блок',
                'verbose_name_plural': 'Стартовые блоки',
            },
        ),
    ]
